using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using FitnessCenter.BO;
using FitnessCenter.BAL;
using FitnessCenter.DAL;

namespace FitnessCenter
{
    public partial class StaffActivity : System.Web.UI.Page
    {

        #region Properties

        public User LoginUser
        {
            get
            {
                var obj = Session["LoginUser"];
                return obj == null ? null : (User)obj;
            }
        }

        public string SortField
        {
            get
            {
                var obj = ViewState["SortField"];
                return obj == null ? "ID" : (string)obj;
            }
            set
            {
                ViewState["SortField"] = value;
            }
        }

        public string SortDir
        {
            get
            {
                var obj = ViewState["SortDir"];
                return obj == null ? "DSC" : (string)obj;
            }
            set
            {
                ViewState["SortDir"] = value;
            }
        }

        public long UserId
        {
            get
            {
                var obj = ViewState["UserId"];
                return obj == null ? 0 : (long)obj;
            }
            set
            {
                ViewState["UserId"] = value;
            }
        }
        public long StatusId
        {
            get
            {
                var obj = ViewState["StatusId"];
                return obj == null ? 0 : (long)obj;
            }
            set
            {
                ViewState["StatusId"] = value;
            }
        }

        public string Mode
        {
            get
            {
                var obj = ViewState["Mode"];
                return obj == null ? "Insert" : (string)obj;
            }
            set
            {
                ViewState["Mode"] = value;
            }
        }

        #endregion


        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                BindRoles();
                BindLeadStatus();
            }
        }

        #region Methods
        private void BindRoles()
        {
            try
            {
                FitnessCenterEntities db = new FitnessCenterEntities();

                var qryEmployees = from emp in db.Users
                                   where emp.UserTypeId != 7 && emp.UserTypeId != 8 && emp.UserTypeId != 9
                                   && emp.UserTypeId != 1 && emp.isActive == true && emp.isDeleted == false
                                   select new
                                   {
                                       FullName = emp.FirstName + " " + emp.LastName,
                                       emp.ID
                                   };

                ddlUsers.DataSource = qryEmployees;
                ddlUsers.DataTextField = "FullName";
                ddlUsers.DataValueField = "ID";
                ddlUsers.DataBind();
                ddlUsers.Items.Insert(0, new ListItem("Select Staff", "0"));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        private void BindLeadStatus()
        {
            try
            {
                ddlStatus.DataSource = UsersController.GetStatus();
                ddlStatus.DataTextField = "status";
                ddlStatus.DataValueField = "ID";
                ddlStatus.DataBind();
                ddlStatus.Items.Insert(0, new ListItem("Select Status", "0"));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private void BindGrid()
        {
            try
            {

                grdStaffActivity.DataSource = UsersController.GetStaffActivity("", SortField, SortDir, txtFromDate.Text, txtToDate.Text, UserId, LoginUser.ClubId, StatusId);
                grdStaffActivity.DataBind();
                if (ddlUsers.SelectedIndex != 0)
                    count.Text = "Total " + Convert.ToString(grdStaffActivity.DataSource) + " Lead Generated By " + ddlUsers.SelectedItem.Text;
                else
                    count.Text = "Total " + Convert.ToString(grdStaffActivity.Rows.Count) + " Lead Generated By All User" ;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        #endregion

        protected void btnSearch_Click(object sender, EventArgs e)
        {
            BindGrid();
        }

        protected void grdStaffActivity_PageIndexChanging(object sender, GridViewPageEventArgs e)
        {

            try
            {
                grdStaffActivity.PageIndex = e.NewPageIndex;
                BindGrid();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected void grdStaffActivity_Sorting(object sender, GridViewSortEventArgs e)
        {
            try
            {
                SortField = e.SortExpression;
                if (SortDir == "ASC")
                    SortDir = "DESC";
                else
                    SortDir = "ASC";
                BindGrid();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected void ddlUsers_SelectedIndexChanged(object sender, EventArgs e)
        {
            UserId = Convert.ToInt64(ddlUsers.SelectedValue);
        }

        protected void ddlStatus_SelectedIndexChanged(object sender, EventArgs e)
        {
            StatusId = Convert.ToInt64(ddlStatus.SelectedValue);
        }


    }
}