//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace FitnessCenter.BO
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Club))]
    [KnownType(typeof(PageMaster))]
    [KnownType(typeof(User))]
    public partial class AccessMaster
    {
        #region Primitive Properties
        [DataMember]
        public virtual long ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual long clubId
        {
            get { return _clubId; }
            set
            {
                if (_clubId != value)
                {
                    if (Club != null && Club.ID != value)
                    {
                        Club = null;
                    }
                    _clubId = value;
                }
            }
        }
        private long _clubId;
        [DataMember]
        public virtual long userId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private long _userId;
        [DataMember]
        public virtual long pageId
        {
            get { return _pageId; }
            set
            {
                if (_pageId != value)
                {
                    if (PageMaster != null && PageMaster.ID != value)
                    {
                        PageMaster = null;
                    }
                    _pageId = value;
                }
            }
        }
        private long _pageId;
        [DataMember]
        public virtual Nullable<bool> CanEdit
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<bool> CanDelete
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<long> updateBy
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime insertDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updateDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> deleteDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<bool> isActive
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isDelete
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual Club Club
        {
            get { return _club; }
            set
            {
                if (!ReferenceEquals(_club, value))
                {
                    var previousValue = _club;
                    _club = value;
                    FixupClub(previousValue);
                }
            }
        }
        private Club _club;
        
    
        [DataMember]
        public virtual PageMaster PageMaster
        {
            get { return _pageMaster; }
            set
            {
                if (!ReferenceEquals(_pageMaster, value))
                {
                    var previousValue = _pageMaster;
                    _pageMaster = value;
                    FixupPageMaster(previousValue);
                }
            }
        }
        private PageMaster _pageMaster;
        
    
        [DataMember]
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion

        #region Association Fixup
    
        private void FixupClub(Club previousValue)
        {
            if (previousValue != null && previousValue.AccessMasters.Contains(this))
            {
                previousValue.AccessMasters.Remove(this);
            }
    
            if (Club != null)
            {
                if (!Club.AccessMasters.Contains(this))
                {
                    Club.AccessMasters.Add(this);
                }
                if (clubId != Club.ID)
                {
                    clubId = Club.ID;
                }
            }
        }
    
        private void FixupPageMaster(PageMaster previousValue)
        {
            if (previousValue != null && previousValue.AccessMasters.Contains(this))
            {
                previousValue.AccessMasters.Remove(this);
            }
    
            if (PageMaster != null)
            {
                if (!PageMaster.AccessMasters.Contains(this))
                {
                    PageMaster.AccessMasters.Add(this);
                }
                if (pageId != PageMaster.ID)
                {
                    pageId = PageMaster.ID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.AccessMasters.Contains(this))
            {
                previousValue.AccessMasters.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.AccessMasters.Contains(this))
                {
                    User.AccessMasters.Add(this);
                }
                if (userId != User.ID)
                {
                    userId = User.ID;
                }
            }
        }

        #endregion

    }
}
