//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace FitnessCenter.BO
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SchemeMaster))]
    public partial class CancellationMaster
    {
        #region Primitive Properties
        [DataMember]
        public virtual long ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual long schemeId
        {
            get { return _schemeId; }
            set
            {
                if (_schemeId != value)
                {
                    if (SchemeMaster != null && SchemeMaster.ID != value)
                    {
                        SchemeMaster = null;
                    }
                    _schemeId = value;
                }
            }
        }
        private long _schemeId;
        [DataMember]
        public virtual bool joiningFee
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool adminFee
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool membershipFee
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool personalTrainingPack
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime insertDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updateDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> deleteDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isActive
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isDelete
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual SchemeMaster SchemeMaster
        {
            get { return _schemeMaster; }
            set
            {
                if (!ReferenceEquals(_schemeMaster, value))
                {
                    var previousValue = _schemeMaster;
                    _schemeMaster = value;
                    FixupSchemeMaster(previousValue);
                }
            }
        }
        private SchemeMaster _schemeMaster;

        #endregion

        #region Association Fixup
    
        private void FixupSchemeMaster(SchemeMaster previousValue)
        {
            if (previousValue != null && previousValue.CancellationMasters.Contains(this))
            {
                previousValue.CancellationMasters.Remove(this);
            }
    
            if (SchemeMaster != null)
            {
                if (!SchemeMaster.CancellationMasters.Contains(this))
                {
                    SchemeMaster.CancellationMasters.Add(this);
                }
                if (schemeId != SchemeMaster.ID)
                {
                    schemeId = SchemeMaster.ID;
                }
            }
        }

        #endregion

    }
}
