//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace FitnessCenter.BO
{
    [DataContract(IsReference = true)]
    public partial class DuePaymentHistory
    {
        #region Primitive Properties
        [DataMember]
        public virtual long Id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string agreementNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual string FullName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string payMode
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> chequeDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chequeNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual string BankName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Branch
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> activationDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> MembershipAmount
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> remainingAmount
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> PaidAmount
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> DueDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> finalAmount
        {
            get;
            set;
        }
        [DataMember]
        public virtual string PackageName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Duration
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> PaymentDate
        {
            get;
            set;
        }

        #endregion

    }
}
