//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace FitnessCenter.BO
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Club))]
    [KnownType(typeof(Lead))]
    [KnownType(typeof(User))]
    [KnownType(typeof(LeadFollowup))]
    [KnownType(typeof(LeadPresentation))]
    public partial class LeadAppointment
    {
        #region Primitive Properties
        [DataMember]
        public virtual long ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime appointmentDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual long leadId
        {
            get { return _leadId; }
            set
            {
                if (_leadId != value)
                {
                    if (Lead != null && Lead.ID != value)
                    {
                        Lead = null;
                    }
                    _leadId = value;
                }
            }
        }
        private long _leadId;
        [DataMember]
        public virtual long clubId
        {
            get { return _clubId; }
            set
            {
                if (_clubId != value)
                {
                    if (Club != null && Club.ID != value)
                    {
                        Club = null;
                    }
                    _clubId = value;
                }
            }
        }
        private long _clubId;
        [DataMember]
        public virtual long userId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private long _userId;
        [DataMember]
        public virtual Nullable<bool> isAttendAppointment
        {
            get;
            set;
        }
        [DataMember]
        public virtual string reasonForNotAttend
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime insertDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updateDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> deleteDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isActive
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isDeleted
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual Club Club
        {
            get { return _club; }
            set
            {
                if (!ReferenceEquals(_club, value))
                {
                    var previousValue = _club;
                    _club = value;
                    FixupClub(previousValue);
                }
            }
        }
        private Club _club;
        
    
        [DataMember]
        public virtual Lead Lead
        {
            get { return _lead; }
            set
            {
                if (!ReferenceEquals(_lead, value))
                {
                    var previousValue = _lead;
                    _lead = value;
                    FixupLead(previousValue);
                }
            }
        }
        private Lead _lead;
        
    
        [DataMember]
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
        
    
        [DataMember]
        public virtual ICollection<LeadFollowup> LeadFollowups
        {
            get
            {
                if (_leadFollowups == null)
                {
                    var newCollection = new FixupCollection<LeadFollowup>();
                    newCollection.CollectionChanged += FixupLeadFollowups;
                    _leadFollowups = newCollection;
                }
                return _leadFollowups;
            }
            set
            {
                if (!ReferenceEquals(_leadFollowups, value))
                {
                    var previousValue = _leadFollowups as FixupCollection<LeadFollowup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLeadFollowups;
                    }
                    _leadFollowups = value;
                    var newValue = value as FixupCollection<LeadFollowup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLeadFollowups;
                    }
                }
            }
        }
        private ICollection<LeadFollowup> _leadFollowups;
        
    
        [DataMember]
        public virtual ICollection<LeadPresentation> LeadPresentations
        {
            get
            {
                if (_leadPresentations == null)
                {
                    var newCollection = new FixupCollection<LeadPresentation>();
                    newCollection.CollectionChanged += FixupLeadPresentations;
                    _leadPresentations = newCollection;
                }
                return _leadPresentations;
            }
            set
            {
                if (!ReferenceEquals(_leadPresentations, value))
                {
                    var previousValue = _leadPresentations as FixupCollection<LeadPresentation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLeadPresentations;
                    }
                    _leadPresentations = value;
                    var newValue = value as FixupCollection<LeadPresentation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLeadPresentations;
                    }
                }
            }
        }
        private ICollection<LeadPresentation> _leadPresentations;

        #endregion

        #region Association Fixup
    
        private void FixupClub(Club previousValue)
        {
            if (previousValue != null && previousValue.LeadAppointments.Contains(this))
            {
                previousValue.LeadAppointments.Remove(this);
            }
    
            if (Club != null)
            {
                if (!Club.LeadAppointments.Contains(this))
                {
                    Club.LeadAppointments.Add(this);
                }
                if (clubId != Club.ID)
                {
                    clubId = Club.ID;
                }
            }
        }
    
        private void FixupLead(Lead previousValue)
        {
            if (previousValue != null && previousValue.LeadAppointments.Contains(this))
            {
                previousValue.LeadAppointments.Remove(this);
            }
    
            if (Lead != null)
            {
                if (!Lead.LeadAppointments.Contains(this))
                {
                    Lead.LeadAppointments.Add(this);
                }
                if (leadId != Lead.ID)
                {
                    leadId = Lead.ID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.LeadAppointments.Contains(this))
            {
                previousValue.LeadAppointments.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.LeadAppointments.Contains(this))
                {
                    User.LeadAppointments.Add(this);
                }
                if (userId != User.ID)
                {
                    userId = User.ID;
                }
            }
        }
    
        private void FixupLeadFollowups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LeadFollowup item in e.NewItems)
                {
                    item.LeadAppointment = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LeadFollowup item in e.OldItems)
                {
                    if (ReferenceEquals(item.LeadAppointment, this))
                    {
                        item.LeadAppointment = null;
                    }
                }
            }
        }
    
        private void FixupLeadPresentations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LeadPresentation item in e.NewItems)
                {
                    item.LeadAppointment = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LeadPresentation item in e.OldItems)
                {
                    if (ReferenceEquals(item.LeadAppointment, this))
                    {
                        item.LeadAppointment = null;
                    }
                }
            }
        }

        #endregion

    }
}
