//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace FitnessCenter.BO
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Lead))]
    [KnownType(typeof(UserTarget))]
    public partial class LeadTypeMaster
    {
        #region Primitive Properties
        [DataMember]
        public virtual long ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string LeadTypeName
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime insertDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updateDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> deleteDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isActive
        {
            get;
            set;
        }
        [DataMember]
        public virtual bool isDeleted
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Lead> Leads
        {
            get
            {
                if (_leads == null)
                {
                    var newCollection = new FixupCollection<Lead>();
                    newCollection.CollectionChanged += FixupLeads;
                    _leads = newCollection;
                }
                return _leads;
            }
            set
            {
                if (!ReferenceEquals(_leads, value))
                {
                    var previousValue = _leads as FixupCollection<Lead>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLeads;
                    }
                    _leads = value;
                    var newValue = value as FixupCollection<Lead>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLeads;
                    }
                }
            }
        }
        private ICollection<Lead> _leads;
        
    
        [DataMember]
        public virtual ICollection<UserTarget> UserTargets
        {
            get
            {
                if (_userTargets == null)
                {
                    var newCollection = new FixupCollection<UserTarget>();
                    newCollection.CollectionChanged += FixupUserTargets;
                    _userTargets = newCollection;
                }
                return _userTargets;
            }
            set
            {
                if (!ReferenceEquals(_userTargets, value))
                {
                    var previousValue = _userTargets as FixupCollection<UserTarget>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserTargets;
                    }
                    _userTargets = value;
                    var newValue = value as FixupCollection<UserTarget>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserTargets;
                    }
                }
            }
        }
        private ICollection<UserTarget> _userTargets;

        #endregion

        #region Association Fixup
    
        private void FixupLeads(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Lead item in e.NewItems)
                {
                    item.LeadTypeMaster = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Lead item in e.OldItems)
                {
                    if (ReferenceEquals(item.LeadTypeMaster, this))
                    {
                        item.LeadTypeMaster = null;
                    }
                }
            }
        }
    
        private void FixupUserTargets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserTarget item in e.NewItems)
                {
                    item.LeadTypeMaster = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserTarget item in e.OldItems)
                {
                    if (ReferenceEquals(item.LeadTypeMaster, this))
                    {
                        item.LeadTypeMaster = null;
                    }
                }
            }
        }

        #endregion

    }
}
